import random

def generate_aws_idea(difficulty):
    easy_ideas = [
        "Serverless Image Processing Pipeline",
        "Microservices Architecture with Lambda and API Gateway",
        "Real-time Data Processing with Kinesis Analytics",
        "Multi-Region Disaster Recovery Solution",
        "Serverless Chat Application with AppSync",
        "Infrastructure as Code (IaC) using AWS CDK",
        "Containerized Application with ECS or EKS",
        "IoT Project with AWS IoT Core",
        "Serverless Workflow with Lambda and Step Functions",
        "Serverless API with Cognito Authentication",
        "Cost Monitoring and Alerting Solution",
        "Machine Learning Model Deployment with SageMaker",
        "Data Lake on AWS with S3 and Athena",
        "Elasticsearch Cluster for Log Analysis",
        "Serverless Email Service with SES and Lambda",
        "Voice-controlled Application with Alexa Skills Kit",
        "Real-time Analytics Dashboard with Quicksight",
        "Video Transcoding Pipeline with MediaConvert",
        "Serverless GraphQL API with AppSync",
        "Continuous Integration/Continuous Deployment (CI/CD) Pipeline",
        "AWS Lambda-backed Custom Resource in CloudFormation",
        "Security Compliance Monitoring and Reporting",
        "Distributed Tracing with AWS X-Ray",
        "Serverless Authentication and Authorization System",
        "Automated Backup and Restore System",
        "Geospatial Data Processing with Location-based Services",
        "Serverless File Upload and Processing System",
        "Interactive Data Visualization with QuickSight",
        "AWS Lambda-backed Chatbot",
        "Highly Available Web Application with Auto Scaling",
        "Serverless GraphQL API with AWS AppSync and DynamoDB",
        "Integration with AWS Translate for Multilingual Support",
        "Distributed Video Streaming Solution with AWS Elemental Media Services",
        "Real-time Collaboration Platform with WebSockets",
        "Serverless Social Media Aggregator",
        "Custom Metrics Dashboard with CloudWatch",
        "Automated Resource Tagging System",
        "Serverless ETL (Extract, Transform, Load) Pipeline",
        "AWS CloudFormation Custom Resource for Third-Party Integration",
        "Serverless Document Search and Retrieval System",
        "Health Monitoring System with AWS IoT and Lambda",
        "Personal Finance Tracker with Budgeting Alerts",
        "Automated Testing Environment Provisioning",
        "Voice-controlled Smart Home Automation",
        "Multi-Cloud Resource Synchronization",
        "Serverless Image Recognition API with Rekognition",
        "Custom DNS Management System with Route 53",
        "AWS CDK Pipeline for Infrastructure Deployment",
        "Automated Incident Response System",
        "Serverless Video Conferencing Solution",
    ]

    intermediate_ideas = [
        "Serverless Image Processing Pipeline",
        "Microservices Architecture with Lambda and API Gateway",
        "Real-time Data Processing with Kinesis Analytics",
        "Multi-Region Disaster Recovery Solution",
        "Serverless Chat Application with AppSync",
        "Infrastructure as Code (IaC) using AWS CDK",
        "Containerized Application with ECS or EKS",
        "IoT Project with AWS IoT Core",
        "Serverless Workflow with Lambda and Step Functions",
        "Serverless API with Cognito Authentication",
        "Cost Monitoring and Alerting Solution",
        "Machine Learning Model Deployment with SageMaker",
        "Data Lake on AWS with S3 and Athena",
        "Elasticsearch Cluster for Log Analysis",
        "Serverless Email Service with SES and Lambda",
        "Voice-controlled Application with Alexa Skills Kit",
        "Real-time Analytics Dashboard with Quicksight",
        "Video Transcoding Pipeline with MediaConvert",
        "Serverless GraphQL API with AppSync",
        "Continuous Integration/Continuous Deployment (CI/CD) Pipeline",
        "AWS Lambda-backed Custom Resource in CloudFormation",
        "Security Compliance Monitoring and Reporting",
        "Distributed Tracing with AWS X-Ray",
        "Serverless Authentication and Authorization System",
        "Automated Backup and Restore System",
        "Geospatial Data Processing with Location-based Services",
        "Serverless File Upload and Processing System",
        "Interactive Data Visualization with QuickSight",
        "AWS Lambda-backed Chatbot",
        "Highly Available Web Application with Auto Scaling",
        "Serverless GraphQL API with AWS AppSync and DynamoDB",
        "Integration with AWS Translate for Multilingual Support",
        "Distributed Video Streaming Solution with AWS Elemental Media Services",
        "Real-time Collaboration Platform with WebSockets",
        "Serverless Social Media Aggregator",
        "Custom Metrics Dashboard with CloudWatch",
        "Automated Resource Tagging System",
        "Serverless ETL (Extract, Transform, Load) Pipeline",
        "AWS CloudFormation Custom Resource for Third-Party Integration",
        "Serverless Document Search and Retrieval System",
        "Health Monitoring System with AWS IoT and Lambda",
        "Personal Finance Tracker with Budgeting Alerts",
        "Automated Testing Environment Provisioning",
        "Voice-controlled Smart Home Automation",
        "Multi-Cloud Resource Synchronization",
        "Serverless Image Recognition API with Rekognition",
        "Custom DNS Management System with Route 53",
        "AWS CDK Pipeline for Infrastructure Deployment",
        "Automated Incident Response System",
        "Serverless Video Conferencing Solution",

    ]

    advanced_ideas = [
        "Serverless Video Processing Pipeline with Media Services",
        "Multi-Region, Multi-AZ Highly Available Microservices Architecture",
        "Real-time Analytics with Kinesis Data Analytics and Lambda",
        "Cross-Account, Cross-Region Disaster Recovery Solution",
        "Voice Recognition System with Amazon Transcribe and Polly",
        "Complex Infrastructure as Code using AWS CDK and CloudFormation",
        "Kubernetes Cluster Management with Amazon EKS",
        "Industrial IoT Platform with Greengrass and IoT Core",
        "Event-Driven Serverless Workflow with EventBridge and Lambda",
        "OAuth2.0 Authentication for Serverless APIs with Cognito",
        "Advanced Cost Management and Anomaly Detection System",
        "Machine Learning Model Deployment with Multi-Model Endpoints",
        "Big Data Analytics with EMR, Spark, and Athena",
        "Elasticsearch Cluster with Kibana for Log and Metrics Analysis",
        "Serverless Email Marketing Platform with SES and Lambda",
        "Custom Skill Development for Alexa for Business",
        "Real-time Financial Data Streaming and Analysis",
        "Video On-Demand Platform with Lambda@Edge",
        "Machine Learning Inference Pipeline with SageMaker",
        "Data Lake Architecture with Glue and Redshift",
        "Security Information and Event Management (SIEM) System",
        "Distributed Tracing and Observability with AWS X-Ray",
        "Fine-Grained Access Control System for Resources",
        "Automated Data Encryption and Key Management System",
        "Geospatial Data Processing and Visualization with Location Services",
        "Serverless GraphQL API with Fine-Tuned Resolvers",
        "AI-Powered Personalized Content Recommendation System",
        "Highly Scalable Chat Application with WebSockets",
        "Automated Compliance Reporting and Auditing",
        "Serverless Data Processing with AWS Step Functions",
        "Integration with AWS Translate for Dynamic Multilingual Support",
        "Real-time Data Streaming with Apache Kafka on AWS",
        "Advanced Load Testing Infrastructure with AWS Fargate",
        "Automated Blue-Green Deployments with AWS CodeDeploy",
        "Serverless Social Media Analytics Platform",
        "Custom Metrics Aggregation and Visualization with CloudWatch",
        "Container Orchestration and Deployment Pipeline with CodePipeline",
        "Automated Incident Response with AWS Security Hub",
        "Serverless Voice-controlled Home Automation System",
        "Advanced Multi-Cloud Resource Orchestration",
        "Data Anonymization and Masking for GDPR Compliance",
        "Real-time Image Recognition API with Custom Models",
        "Custom DNS Management System with Private Hosted Zones",
        "AWS CDK Pipeline for Multi-Environment Deployments",
        "Advanced Multi-Tier Architecture with Auto Scaling",
        "Cross-Account, Cross-Region Service Discovery with CloudMap",
        "Real-time Video Conferencing Solution with Chime SDK",
        "Serverless Natural Language Processing (NLP) API",
        "Blockchain Integration for Secure Transactions",
        "Multi-Cloud Service Mesh Implementation ",
    ]

    if difficulty == "easy":
        return random.choice(easy_ideas)
    elif difficulty == "intermediate":
        return random.choice(intermediate_ideas)
    elif difficulty == "advanced":
        return random.choice(advanced_ideas)
    else:
        return "Invalid difficulty level. Please choose 'easy', 'intermediate', or 'advanced'."

if __name__ == "__main__":
    print("Choose the difficulty level: 'easy', 'intermediate', or 'advanced'")
    user_choice = input().lower()

    idea = generate_aws_idea(user_choice)
    print("\nYour randomly assigned Python project idea is:")
    print(idea)
